services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    env_file:
      - backend/.env
    volumes:
      - ./public:/app/public:ro
    restart: unless-stopped

  website:
    build:
      context: .
      dockerfile: docker/website.Dockerfile
    container_name: neocities-website
    ports:
      - "9500:80"
    depends_on:
      - backend
    restart: unless-stopped
